index:
    path: /
    controller: App\Controller\LoginController::login
entry_list:
    path: /list/{page}
    controller: App\Controller\ListController::list
    defaults:
        page: 1
    requirements:
        page: '\d+'
entry_add:
    path: /add
    controller: App\Controller\ListController::add
entry_view:
    path: /view/{id}
    controller: App\Controller\ListController::view
    defaults:
        id: 1
    requirements:
        id: '\d+'
entry_delete:
    path: /delete/{id}
    controller: App\Controller\ListController::delete
    defaults:
        id: 1
    requirements:
        id: '\d+'
entry_approve:
    path: /approve/{id}
    controller: App\Controller\ListController::approve
    defaults:
        id: 1
    requirements:
        id: '\d+'
entry_revoke:
    path: /revoke/{id}
    controller: App\Controller\ListController::revoke
    defaults:
        id: 1
    requirements:
        id: '\d+'
    